version: '3'
services:
  node:
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=example.com
      - LETSENCRYPT_HOST=example.com
      - LETSENCRYPT_EMAIL=daniel@example.com
    volumes:
      - .:/home/node
      - /home/node/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: unless-stopped
    command: --smallfiles
    volumes:
      - ./backups:/backups
networks:
  default:
    external:
      name: nginx-proxy
